name: rules
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  provider: ^6.1.1
  yaml: ^3.1.2
  fpdart: ^1.1.0
  equatable: ^2.0.5
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  dio: ^5.4.1
  hive: ^2.2.3
  golden_toolkit: ^0.15.0
  meta: ^1.10.0
  test_api: ^0.6.1
  mocktail: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^8.1.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  easy_plugin:
    path: ./packages/easy_plugin
  anis_test:
    path: ./packages/anis_test
  custom_lint: ^0.6.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
